server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # SPA (frontend routing)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # API & Backoffice → backend
   location ~ ^/(api|backoffice)/ {
       proxy_pass http://clinic-api-staging:3000;
   }
}